In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
print iris.feature_names
print iris.target_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
print iris.data[0]

[ 5.1  3.5  1.4  0.2]


In [5]:
from sklearn import tree
import numpy as np
test_idx= [0,50,100]

In [6]:
#training data

train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [7]:
#testing data

test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [8]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [9]:
print test_target
print clf.predict(test_data)

[0 1 2]
[0 1 2]


In [17]:
#visualization code
'''from sklearn.externals.six import StringIO
import pydot
dot_data = StringIO()
tree.export_graphviz(clf, out_file=None, 
                         feature_names=iris.feature_names,  
                         class_names=iris.target_names,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = pydot.graph_from_dot_data(dot_data.getvalue())  
graph.write_pdf("iris.pdf") ''' 

'from sklearn.externals.six import StringIO\nimport pydot\ndot_data = StringIO()\ntree.export_graphviz(clf, out_file=None, \n                         feature_names=iris.feature_names,  \n                         class_names=iris.target_names,  \n                         filled=True, rounded=True,  \n                         special_characters=True)  \ngraph = pydot.graph_from_dot_data(dot_data.getvalue())  \ngraph.write_pdf("iris.pdf") '